/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

//! This crate exists to test version mismatches between the scaffolding and the bindings.  This
//! includes:
//!
//!   - The scaffolding is generated by one version of UniFFI and the bindings are generated by
//!     an incompatible one (i.e one with a different `UNIFFI_CONTRACT_VERSION`)
//!   - The scaffolding is generated by one version of the library API, and the bindings are
//!     generated with another.  This means either the UDL changed or the Rust code wrapped by a
//!     proc-macro changed. This crate uses features to simulate these types of mismatches

#[cfg(not(feature = "proc_macro_v2"))]
#[uniffi::export]
fn a_proc_macro_export() -> u32 {
    1
}

#[cfg(feature = "proc_macro_v2")]
#[uniffi::export]
fn a_proc_macro_export() -> i32 {
    2
}

fn a_udl_function() -> u32 {
    1
}

include!(concat!(env!("OUT_DIR"), "/api_v1.uniffi.rs"));
