[package]
name = "bindings-ir-tests"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
bindings-ir = { path="../bindings-ir" }
bytes = "1"
camino = "1.0.8"
cargo_metadata = "0.14"
lazy_static = "1.4"
once_cell = "1.12"
