[package]
name = "render-macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
once_cell = "1"
itertools = "0.10"
regex = "1"
syn = { version = "1", features = ["extra-traits", "full"] }
